# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b0C1jnLWjLZQvDTVqrsih4ezwmvuLScy
"""

import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(nrows=1)
x0 = -5
x1 = 5
xmin = -1
xmax = 2
ax.set_ylim(-1, 1)
ax.set_xlim(x0 - 0.4, x1 + 0.4)
ax.set_xticks(range(x0, x1 + 1))
ax.set_yticks([])
ax.tick_params(axis='x', direction='inout', length=10)
ax.spines['bottom'].set_position('zero')
ax.spines['bottom'].set_zorder(0)
for dir in ['left', 'right', 'top']:
    ax.spines[dir].set_visible(False)
ax.plot([xmin, xmax], [0, 0], color='red', lw=1)
ax.plot([x0 - 0.2, x0 - 0.4, x0 - 0.2], [0.2, 0, -0.2], color='black', lw=1)
ax.plot([x1 + 0.2, x1 + 0.4, x1 + 0.2], [0.2, 0, -0.2], color='black', lw=1)
ax.plot(p, 0, linestyle='', marker='o', fillstyle='full', markerfacecolor='white',
        markersize=-1, lw=2, zorder=2)
ax.set_aspect('equal')